# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVd_yOLKTA5jRTS5Evbu89nOS3jsuEyf
"""

from flask import Flask, request
from flask_restful import Resource, Api

app = Flask(__name__)
api = Api(app)

# Dados da conta bancária
conta_bancaria = {
    "1234-5": {
        "saldo": 0.0
    }
}

class Saldo(Resource):
    def get(self, conta_id):
        if conta_id in conta_bancaria:
            return {"saldo": conta_bancaria[conta_id]["saldo"]}
        else:
            return {"message": "Conta não encontrada"}, 404

class Transacao(Resource):
    def post(self, conta_id):
        if conta_id in conta_bancaria:
            dados_transacao = request.json
            if 'op' in dados_transacao and 'valor' in dados_transacao:
                if dados_transacao['op'] == 'deposito':
                    conta_bancaria[conta_id]["saldo"] += dados_transacao["valor"]
                    return {"message": "Depósito efetuado com sucesso"}
                elif dados_transacao['op'] == 'saque':
                    if conta_bancaria[conta_id]["saldo"] >= dados_transacao["valor"]:
                        conta_bancaria[conta_id]["saldo"] -= dados_transacao["valor"]
                        return {"message": "Saque efetuado com sucesso"}
                    else:
                        return {"message": "Saldo insuficiente"}, 400
                else:
                    return {"message": "Operação inválida"}, 400
            else:
                return {"message": "Dados de transação incompletos"}, 400
        else:
            return {"message": "Conta não encontrada"}, 404

api.add_resource(Saldo, '/contas/<string:conta_id>/saldo')
api.add_resource(Transacao, '/contas/<string:conta_id>/transacao')

if __name__ == '__main__':
    app.run(debug=True, port=1512)